baseURL = 'http://auroratapas.com/'
languageCode = 'en-us'
title = 'Aurora Tapas'
description = 'Una experiencia para compartir'
defaultContentLanguage = "es"

[params]
    defaultDescription = "Una experiencia para compartir"
    defaultKeywords = ["Aurora", "Bar", "Tapas", "Aurora Tapas", "Bar de Tapas"]
    
    author = "Pedro Victor Navarrete Alejo"

    date_format = "Enero 2, 2024"

    logo = "imgs/logo.png"
    banner = "imgs/banner.jpg"
    logo_small = "imgs/favicon.png"
    address = "Calle Real del Jigüe No. 83 entre Guarabo y San José, Trinidad, Sancti Spiritus, Cuba"
    phone = "(+53 5) 447-4452"
    email = "auroratapas@gmail.com"
    copyright = "Copyright (c) 2024, AuroraTapas; Todos los derechos reservados."

    formsubmit_action = "https://formsubmit.co/auroratapas@gmail.com"